name: Publish Docker image

on:
  push:
    branches:
    - master
    - dev

jobs:
  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_image: ubuntu-14.04
            arch: linux/amd64
          - docker_image: manylinux2014_aarch64
            arch: linux/arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract tag for Docker
        id: tag
        shell: bash
        run: |
            branch=${GITHUB_REF#refs/heads/}
            docker_tag=${{ matrix.docker_image }}-${branch}
            docker_tag=${docker_tag%-master}
            echo "::set-output name=docker_tag::${docker_tag}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        if: matrix.arch != 'linux/amd64'
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.workspace }}/dockers/${{ matrix.docker_image }}/
          push: true
          platforms: ${{ matrix.arch }}
          tags: lightgbm/vsts-agent:${{ steps.tag.outputs.docker_tag }}
